artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_name: https://github.com/BhorSant/Chicken-disease/blob/main/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion